CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

- style guides
- code of conduct

Fix #49 - Beef-up the CONTRIBUTING.md content

---

app/controllers/home_controller.rb
app/models/event.rb
app/views/layouts/_sidebar.html.erb

[WIP] [Feature] Fixes #59 - Display recent events in home sidebar

---

app/views/layouts/_sidebar.html.erb

Handled no event case

---

db/migrate/20140929233719_create_events.rb
db/migrate/20140930000502_create_companies.rb

Fix migrations, ensures they can be run from the start

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.css.scss
app/assets/stylesheets/modules/_alert.scss
app/views/layouts/_flash.html.erb
app/views/layouts/_header.html.erb
app/views/layouts/application.html.erb
spec/features/authentication_spec.rb
spec/spec_helper.rb

- Add login/out links
- Add flash message
- Add specs to test login/out

Issue 58: Implement authentication

---

Gemfile
Gemfile.lock
README.md

Also updated the README to mention bundler and its minimal version.

[chore] Fixes #88 - Fix gem dependencies as notified by gemnasium

---

.coffeescript-style.json
.hound.yml
.ruby-style.yml
.scss-style.yml
CONTRIBUTING.md

Explicitely adds default configuration (for later tweaking):
- ruby
- coffeescript
- scss

[chore] Fixes #92 - Setup houndci.com

---

app/dashboards/page_dashboard.rb

This was raising an exception in production.  Fixes #91
@benichu Quick check and merge?

Correctly name space class

---

app/models/location.rb
db/migrate/20151204170038_make_locations_name_required.rb
db/schema.rb
spec/models/location_spec.rb

Locations: make 'name' a required field

---

app/assets/stylesheets/application.css.scss
app/assets/stylesheets/mixins/_colors.scss
app/assets/stylesheets/modules/_header.scss
app/assets/stylesheets/news_item.scss
app/views/layouts/_header.html.erb

Clickable header title Montreal.rb

---

.gitignore
Gemfile
Gemfile.lock
config/newrelic.yml

Resolves #111 - Setup Newrelic
This is simply the configuration part. To test and ensure all is well we'd need to deploy to production and create some traffic. Considering the app is in maintenance mode, we could leave this to later.
Standard integration on production, nothing particular.

Resolves #111 - Setup Newrelic

---

app/controllers/admin/application_controller.rb
app/controllers/application_controller.rb
app/views/layouts/_header.html.erb
db/migrate/20151203025820_add_admin_to_users.rb
db/schema.rb
spec/factories/user.rb
spec/features/authentication_spec.rb

- Added a hack for admin user (to be fixed based on advice), for this one I wasn't sure how to handle:
* Should I add a new admin(boolean) column to the user table?
* Should I add a a new type(string) column to the user table?  
- Redirect to admin area if user is admin
- Added logic for admin authentication
- Added a link to admin area if admin user is signed-in
- Specs will be fixed and new ones will be added when I fix the admin user situation :)

Add Auth to Admin Area

---

app/models/event.rb
app/models/location.rb
db/migrate/20151204174632_make_events_location_id_required.rb
db/schema.rb
spec/models/event_spec.rb

Fix for issue #107.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/montrealrb/montreal.rb/116)

Events: make 'location_id' a required field

---

app/assets/stylesheets/modules/_footer.scss
app/assets/stylesheets/modules/_navigation.scss
app/controllers/pages_controller.rb
app/views/layouts/_header.html.erb
app/views/layouts/application.html.erb
app/views/pages/about.html.erb
config/routes.rb

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/montrealrb/montreal.rb/152)

[chore] Fixes #149 - Prepare Website MVP UI for launch

---

CONTRIBUTING.md
README.md

It's important these instructions are as clear as possible.

improving the chances of having a pull request accepted

---

CONTRIBUTING.md
README.md

Reverts montrealrb/Montreal.rb#169

Revert "improving the chances of having a pull request accepted"

---

db/seeds.rb
spec/controllers/news_item_controller_spec.rb
spec/controllers/pages_controller_spec.rb
spec/factories/events.rb
spec/factories/jobs.rb
spec/factories/locations.rb
spec/factories/news_items.rb
spec/factories/organizations.rb
spec/factories/pages.rb
spec/factories/user.rb
spec/features/authentication_spec.rb
spec/models/news_item_spec.rb
spec/support/factory_girl.rb

* Wrote the rest of the factories
+ Added test for factory lint
+ Added seeds to get developers started faster
* Fixed tests to use factory traits, rather than separate factories

Better factories with linting and traits

---

Gemfile
Gemfile.lock
app/models/job.rb
config/initializers/active_record_extensions.rb
spec/models/job_spec.rb
spec/spec_helper.rb

This is the patch written by @AndyObtiva rebased.

Fix issues/93 job validation

---

.ruby-style.yml
app/dashboards/company_dashboard.rb
app/dashboards/dashboard_manifest.rb
app/dashboards/event_dashboard.rb
app/dashboards/job_dashboard.rb
app/dashboards/location_dashboard.rb
app/dashboards/meetup_dashboard.rb
app/dashboards/news_item_dashboard.rb
app/dashboards/organization_dashboard.rb
app/dashboards/page_dashboard.rb
app/dashboards/talk_dashboard.rb
app/dashboards/user_dashboard.rb
app/dashboards/vote_dashboard.rb
app/models/job.rb

*Updated rubocop for better linting
*Fixed any issues raised by rubocop
*Updated style config from houndci.com, keeping Montreal.rb's
modifications

Update linting to match houndci.com's

---

app/dashboards/event_dashboard.rb
app/models/event.rb
db/migrate/20160308004823_add_state_to_events.rb
db/schema.rb
spec/controllers/events_controller_spec.rb
spec/factories/events.rb
spec/models/event_spec.rb

[issue #105] add state to event

---

app/assets/stylesheets/application.css.scss
app/assets/stylesheets/components/_event.css.scss
app/assets/stylesheets/mixins/_colors.scss
app/views/events/_event.html.erb
app/views/events/index.html.erb
app/views/events/show.html.erb

Closes #13 
Event are nicely displayed with time and location info, talks title and descriptions as well.

Display all events relevant infos

---

Gemfile
Gemfile.lock
app/models/user.rb
spec/models/user_spec.rb

fix GitHub authentication

---

app/dashboards/user_dashboard.rb

#203 Added admin checkbox to user dashboard

---

README.md

The Gemfile is now using 2.3.1.

Set the right ruby version in README

---

Gemfile
Gemfile.lock
app/controllers/events_controller.rb
app/controllers/home_controller.rb
app/controllers/jobs_controller.rb
app/controllers/organizations_controller.rb
config/environments/development.rb
spec/controllers/home_controller_spec.rb

When I installed the repo, I found some N+1 queries in some page.
I installed Bullet to help tracking N+1.
I hope this will help 😄

Fix N+1 query errors

---

app/views/layouts/_footer.html.erb

[chore] Fixes #233 - Remove #footer link to wiki#changelog because not updated

---

app/controllers/admin/events_controller.rb
app/models/event.rb
spec/controllers/admin/events_controller_spec.rb
spec/models/event_spec.rb

Added methods in model and controller with tests (on model only)

Added talk unlinking on event deletion

---

README.md
app/models/user.rb
config/database.yml
db/schema.rb

Makes it easier to start with development

use sqlite3 for development

---

app/controllers/admin/contacts_controller.rb
app/dashboards/contact_dashboard.rb
app/dashboards/dashboard_manifest.rb
app/models/concerns/authorable.rb
app/models/contact.rb
app/models/event.rb
app/models/job.rb
app/models/news_item.rb
db/migrate/20170523223432_create_contacts.rb
db/migrate/20170523233820_add_user_to_contacts.rb
db/schema.rb
spec/controllers/admin/contacts_controller_spec.rb
spec/factories/contacts.rb
spec/models/contact_spec.rb
spec/models/event_spec.rb
spec/models/job_spec.rb
spec/models/news_item_spec.rb
spec/support/authorable_spec_helper.rb

I decide to work on the contacts book. I hope it will be useful.
I move the validation and the association of the author inside a new concern.
fix #212

[Feature][Issue 212] Contact book

---

app/views/layouts/_footer.html.erb

Removed Google groups link from footer and added links for meetup, youtube, and facebook.

add social media links 
